krakend/krakend-ce

Makefile

We need to install dep to manage vendors.

Install/Update 'dep'

---

.gitignore
Dockerfile
Makefile
README.md
builder/alpine/Dockerfile
builder/files/krakend.conf
builder/files/krakend.conf.el6
builder/files/krakend.init
builder/files/krakend.service
builder/scripts/postrm.deb
builder/scripts/postrm.rpm
builder/scripts/preinst-debian-wheezy.deb
builder/scripts/preinst.deb
builder/scripts/preinst.rpm
builder/scripts/prerm.deb
builder/scripts/prerm.rpm
builder/skel/.gitignore

Added scripts to create rpm, deb and binary packages and build the docker container for the docker hub.

Package builder and Krakend docker container

---

executor.go

panic was caused by err overridden by nil and user in logger.Error method

FIX: panic when unable to initialize gologging error and correctly initialized logging.

---

Gopkg.lock
Gopkg.toml
README.md
backend_factory.go

This PR includes the krakend-httpcache module into the krakend-ce binary

Add krakend-httpcache module

---

Gopkg.lock
Gopkg.toml

Upgrade to krakend-0.4.2

---

Gopkg.lock
Gopkg.toml
backend_factory.go
executor.go
handler_factory.go
proxy_factory.go

as requested in https://github.com/devopsfaith/krakend/issues/109, this PR integrates the new opencensus component

opencensus component added

---

Gopkg.lock
Gopkg.toml
Makefile

Release fixing the KrakenD-opencensus module.

Update opencensus module and set the KrakenD-ce version to 0.5.1

---

Gopkg.lock
Gopkg.toml
Makefile
builder/alpine/Dockerfile
executor.go
handler_factory.go
krakend.json
router_engine.go
sd.go

This PR adds the following components:
- JOSE: 2 endpoint handlers for signing and verifying JWT
- BloomFilter: eventually consistent, distributed bloomfilter for revoking valid JWT
- Consul: SD integration able to register the BF service

Add JOSE layer

---

Makefile

dep updated to 0.5.0

---

Gopkg.lock
Gopkg.toml
Makefile

This PR updates all the pending deps and bumps the v0.6.0

Bump version 0.6.0

---

Gopkg.lock
Gopkg.toml
router_engine.go

this PR updates the httpsecure module to v0.6.0

httpsecure updated

---

.travis.yml
Gopkg.lock
Gopkg.toml
Makefile
builder/alpine/Dockerfile

This PR updates all the pending deps and bumps the v0.6.1

Bump version 0.6.1

---

Gopkg.lock
Gopkg.toml
proxy_factory.go

This PR adds the jsonschema module to the KrakenD CE

Add JSON schema request validator

---

Makefile
backend_factory.go
cmd/krakend-ce/main.go
encoding.go
executor.go
handler_factory.go
proxy_factory.go
router_engine.go
sd.go

so the rest of the lib can be reused in other commands

move the main function to a dedicated package

---

Gopkg.lock
executor.go

so we can set a diferent format in the gelf writer.

Update krakend-gologging 

---

Gopkg.lock
backend_factory.go

📄 Documentation is on https://github.com/devopsfaith/krakend-documentation/pull/15

Add the logger to the circuit breaker

---

Gopkg.lock
Gopkg.toml
executor.go

🚀 Needs https://github.com/devopsfaith/krakend-logstash/pull/1 in order to be this build on green.
☝️ Also, in order to log with custom format: https://github.com/devopsfaith/krakend-gologging/pull/2
📄 Documentation for all logstash related: https://github.com/devopsfaith/krakend-documentation/pull/13

Add logstash logger integration

---

Gopkg.lock
Gopkg.toml
handler_factory.go

upgrade jose component to 0.8.0

---

Gopkg.lock
Gopkg.toml

oauth2 client credentials module upgraded to version 0.8.0

---

Gopkg.lock
Gopkg.toml

so the fix for devopsfaith/krakend#198 is already available at master

krakend version updated

---

Gopkg.lock
Gopkg.toml

this PR upgrades the metrics and influxdb modules

Upgrade the metrics modules

---

.gitignore
Gopkg.lock
Gopkg.toml
backend_factory.go
executor.go
proxy_factory.go
tests/fixtures/krakend.json
tests/fixtures/specs/cel-1.json
tests/fixtures/specs/cel-2.json
tests/fixtures/specs/cel-3.json
tests/fixtures/specs/cel-4.json
tests/fixtures/specs/cel-5.json

this PR introduces the [CEL module](https://github.com/devopsfaith/krakend-cel) into the KrakenD official binary (and the required integration tests)

Include the CEL module

---

Gopkg.lock
Gopkg.toml
tests/fixtures/krakend.json
tests/fixtures/specs/flatmap_1.json
tests/integration.go

as requested at #14, this PR introduces the flatmap based filters so elements in collections can be manipulated just like any other element in a map

flatmap filter added

---

Gopkg.lock

This PR adds the two most recent perf improvements from the KrakenD framework
- use the string builder instead of appending arrays
- use a type switch instead of always going with fmt

Include recent KrakenD pref improvements

---

Gopkg.lock
Gopkg.toml
cmd/krakend-ce/main.go

this PR includes the latest config error improvements from the KrakenD frameworks and the krakend-viper component

config errors improved

---

cmd/krakend-ce/main.go

as requested at #104 this PR defines a new envvar for the flexibleconfig template param

templates env_var added

---

Gopkg.lock
Gopkg.toml

this PR introduces the cookie, martianurl, port, priority and stash packages from the martian lib and a custom static modifier from the adapter itself

martian module updated

---

Gopkg.lock
tests/fixtures/specs/param_forwarding_2.json

if present in the `headers_to_pass` set

forward the user-agent header

---

Gopkg.lock
Gopkg.toml
backend_factory.go
executor.go

this PR includes the [krakend-pubsub](https://github.com/devopsfaith/krakend-pubsub) module

pubsub module added

---

Gopkg.lock
Gopkg.toml
backend_factory.go

as requested at #114 this pr includes the krakend-lambda backend factory into the CE factory stack

krakend-lambda module added

---

go.mod
go.sum
tests/integration.go

This PR fixes the error returned by the gateway when the XML response from the backend does not ends with a line break
`xml.Decoder.Token() - XML syntax error on line XX: unexpected EOF`
The issue was also reported to the mxj project (https://github.com/clbanning/mxj/issues/63)

Xml line break

---

go.mod
go.sum
tests/fixtures/specs/cors_1.json
tests/fixtures/specs/cors_2.json

cors module updated

---

go.mod
go.sum

this PR includes https://github.com/devopsfaith/krakend/issues/264 into the 0.10 branch

Flatmap: keep empty collections and maps

---

go.mod
go.sum

version of the httpsecure component updated

---

go.mod
go.sum

... so the response can be formatted

Update the lambda mod

---

go.mod
go.sum

include fix for the request body setters of the LUA router middleware (https://github.com/devopsfaith/krakend-lua/pull/2)

LUA router request body setters

---

go.mod
go.sum

so fix https://github.com/devopsfaith/krakend-lua/pull/3 is added

lua module updated

---

go.mod
go.sum

closes https://github.com/devopsfaith/krakend-ce/issues/146

jose package upgraded to v1.1.0

---

backend_factory.go
executor.go
handler_factory.go
plugin.go
proxy_factory.go
router_engine.go
sd.go

This PR introduces a new composable Executor easier to use

Interface extension

---

Dockerfile
Dockerfile.alpine

Run KrakenD inside docker as an unprivileged user.

Create a krakend user and group in Docker to avoid using root

---

Makefile

Add ca-certificates as dependency on debian

---

go.mod
go.sum

opencensus module updated

---

go.mod
go.sum

fixes https://github.com/devopsfaith/krakend/issues/369

krakend prefix added to the envvars

---

go.mod
go.sum

support for namespaced custom claims added

---

executor.go
go.mod
go.sum
router_engine.go
tests/fixtures/specs/cors_5.json

CORS mw added as a RunServer wrapper so it's always executed

Make sure the CORS mw is always executed

---

Makefile
backend_factory.go
go.mod
go.sum
tests/fixtures/specs/backend_301.json
tests/fixtures/specs/backend_302.json
tests/fixtures/specs/backend_303.json
tests/fixtures/specs/backend_307.json
tests/fixtures/specs/cors_5.json
tests/fixtures/specs/detail_error.json
tests/fixtures/specs/no-op.json
tests/fixtures/specs/param_forwarding_1.json
tests/fixtures/specs/param_forwarding_2.json
tests/fixtures/specs/param_forwarding_3.json
tests/fixtures/specs/param_forwarding_4.json
tests/fixtures/specs/query_forwarding_1.json
tests/fixtures/specs/query_forwarding_2.json
tests/fixtures/specs/query_forwarding_3.json
tests/fixtures/specs/sequential_1.json
tests/fixtures/specs/timeout.json
tests/fixtures/specs/xml_2.json

so it receives the bac…kend configurations. 
Updated deps to use latest opencensus and lura version to include other bugfixes in the framework.

Fix call to the opencensus HTTPExecutorFactory

---

README.md

This commit update logo image path and some links inside README.md

Update some paths and links in README.md

---

Dockerfile
Makefile

Adds the default config file to the docker container.
Removes the VOLUME since it does nothing here.
Set a fixed uid for the user. #196

Dockerfile: Add a default config file. Create the user with a fixed uid #196.

---

go.mod
go.sum
krakend.json
tests/fixtures/krakend.json

to `input_headers` and `input_query_string`
Merge when Lura is updated

Rename headers_to_pass and querystring_params 

---

go.mod
go.sum

ratelimit pkg updated

---

go.mod
go.sum

this PR fixes the log prefix for the amqp agent

amqp pkg updated

---

Makefile
builder/files/krakend-logrotate
builder/files/krakend.conf-rsyslog

configuration files and as depencencies of the deb and rpm packages.

Add rsyslog and logrotate

---

Makefile
tests/fixtures/specs/backend_301.json
tests/fixtures/specs/backend_302.json
tests/fixtures/specs/backend_303.json
tests/fixtures/specs/backend_307.json
tests/fixtures/specs/cel-7.json
tests/fixtures/specs/cors_5.json
tests/fixtures/specs/detail_error.json
tests/fixtures/specs/no-op_1.json
tests/fixtures/specs/param_forwarding_1.json
tests/fixtures/specs/param_forwarding_2.json
tests/fixtures/specs/param_forwarding_3.json
tests/fixtures/specs/param_forwarding_4.json
tests/fixtures/specs/query_forwarding_1.json
tests/fixtures/specs/query_forwarding_2.json
tests/fixtures/specs/query_forwarding_3.json
tests/fixtures/specs/sequential_1.json
tests/fixtures/specs/timeout.json
tests/fixtures/specs/xml_2.json

Signed-off-by: Daniel Ortiz <dortiz@krakend.io>

Bump version to 2.1.1

---

Dockerfile
Dockerfile-plugin-builder
Makefile
find_glibc.sh

Signed-off-by: Daniel Ortiz <dortiz@krakend.io>

Add a plugin-builder container and add the OS info to the build.

---

tests/fixtures/krakend.json
tests/fixtures/specs/param_forwarding_4.json
tests/integration.go

check that the request body is passed to the backend

---

tests/integration.go

In the integration tests requests if the Host header exists.
Signed-off-by: Daniel Ortiz <dortiz@krakend.io>

Set the request Host

---

Dockerfile-builder

Signed-off-by: Daniel Ortiz <dortiz@krakend.io>

Remove git from alpine builder, provided version it's too old.

---

go.mod
go.sum

This PR updates the amqp lib so https://github.com/krakendio/krakend-amqp/pull/18 is included
Closes https://github.com/krakendio/krakend-ce/issues/486

Update amqp lib

---

executor.go
go.mod
go.sum

Initialize the global cache for the JWK clients if enabled

---

go.mod
go.sum

XML: escape special chars

---

tests/integration.go

To be able to run several servers, we would need a new interface for `tests.BackendBuilder` that allows us to return an interface instead of an `http.Server` directly.

Add integration tests composable backend builder

---

go.mod
go.sum

Update to krakend-lua v2.1.1

---

tests/integration.go

Allow to execute extra test steps sequentially for a test case.

add next extra tests for test case

---

tests/integration.go

support gziped body response in tests

support gziped body response in tests

---

go.mod
go.sum

update to krakend-otel 0.12.0
