krakend/krakend-ce

.travis.yml
Dockerfile
Gopkg.lock
Makefile
README.md
builder/alpine/Dockerfile
executor.go
krakend.json
router_engine.go

Since it's already provided in the new krakend-metrics middleware.
It also updates golang to 1.10.2 and fix the Dockerfile.

Remove the stats endpoint. Golang 1.10.2

---

Gopkg.lock
Gopkg.toml

Fixes issue #37 
Updates the bloomfilter dependency to fix the `runtime.support_avx` problem on go1.11.

Go1.11 mac fix

---

Gopkg.lock
Gopkg.toml
executor.go

Update middleware logs to Warning (instead of Error).
Add information about the port used.
Update the bloomfilter package to fix it's log output.

Log information update

---

Gopkg.lock
Gopkg.toml

as requested at #72, this PR upgrades the etcd client to the v3.3.12 while still using the `github.com/coreos/etcd/client` package instead of `github.com/coreos/etcd/clientv3`

etcd client upgraded to v3.3

---

.gitignore
cmd/krakend-integration/main.go
tests/integration.go
tests/integration_example_test.go
tests/integration_test.go

this PR moves the logic of the integration tests into a small set of exposed components so the package can be used as a lib (running without the testing pkg).
It also adds a new cmd for building a binary so the KrakenD-CE integration tests can also be executed in an environment without `go`. Sample execution of the binary at its directory:
```
$ ./krakend-integration -krakend_bin_path "../.././krakend" \\
-krakend_config_path "../../tests/fixtures/krakend.json" \\
-krakend_specs_path "../../tests/fixtures/specs"
query_forwarding_1: ok
query_forwarding_3: ok
no-op: ok
param_forwarding_3: ok
query_forwarding_2: ok
sequential_1: ok
timeout: ok
detail_error: ok
negotitate_json: ok
param_forwarding_1: ok
router_405: ok
rss: ok
collection: ok
negotitate_plain: ok
router_404: ok
sequential_2: ok …
```

Expose the utilities for integration tests

---

Gopkg.lock
Gopkg.toml
executor.go
handler_factory.go

so every endpoint can be checked against an individual rejecter (if required)

Inject a rejecter factory

---

encoding.go
go.mod
go.sum
tests/fixtures/krakend.json
tests/fixtures/specs/xml_1.json
tests/fixtures/specs/xml_2.json

The `negotiate` render uses the `encoding/xml` pkg from the stdlib, making it hard for the gateway to return XML generated from maps of interfaces. This PR registers a `xml` render using the mxj lib making it possible to return any response as XML

xml render

---

router_engine.go

when running the gateway without the `-d` flag, the gin router must be set to 'release'

Link the gin debug mode to the debug flag

---

go.mod
go.sum

include https://github.com/devopsfaith/krakend-lambda/pull/4 in order to pass proper client context values

lambda version updated

---

Dockerfile
Dockerfile.alpine
Makefile
builder/alpine/Dockerfile

There is a fix for a problem #177 when krakend with custom plugin could not be started.
Developers in #krakend slack channel noticed that replace alpine to another distro helps with this issue. I've dropped alpine support and replace it to debian:buster.
It slightly increases docker image size, but makes plugins work.

Fix #177 Added Debian as a main image builder for `krakend`, updated alpine builder and version

---

cmd/krakend-integration/main.go
tests/integration.go

this PR improves the integration test runner by:
- returning a non zero exit code when an error is detected
- collecting all the errors before closing the test
- passing envars to the krakend instance under test (with filters)

better error reporting added to the integration test runner

---

tests/fixtures/specs/cors_5.json
tests/integration.go

Add a boolean flag `client_not_follow_redirects` to krakend-integration to allow the client not to follow http redirects

Disable IT http client to follow redirections

---

go.mod
go.sum

this PR replaces the original `github.com/gregjones/httpcache` module with the branch from this PR (https://github.com/gregjones/httpcache/pull/104)
closes github.com/luraproject/lura/issues/335

replace the original http cache with the fixed fork

---

tests/fixtures/specs/detail_error.json
tests/integration.go

@kpacha if that makes sense to you I could update all test scenarios to be declared as json.
We have been using `krakend-integration` as a tool in our CI pipeline and it is sometimes inconvenient to define the response `Body` as string since it does full match. With this change json objects may be compared no matter how the keys are sorted.

Declare expected response as either string or json object

---

tests/fixtures/specs/jsonschema_1.json
tests/integration.go

This PR aims to ease the declaration of integration tests using krakend-integration, `input.Body` may now be declared as string (escaping quotes) or as an embedded object.

Declare krakend-integration input body as either string or object

---

README.md

Currently the README has "Security::" in it, instead of "Security:". This is a simple change to fix that.

Drop extraneous : from README

---

executor.go

Also log the succesful start of the component. Prints Krakend Version on startup.

Gologging should not log an error if the configuration is not present

---

executor.go

since if you return an interface that have an underlying pointer it's never nil.

Set the gelfWriter to nil if there's an error in gelf

---

.github/workflows/security.yml

This does a security scan for hardcoded secrets and vulnerable software
dependencies. This will hopefully help us prioritize dependency updates
in such a way that we don't keep vulnerable dependencies for too long.
Note that this should only be detecting `HIGH` and `CRITICAL`
vulnerabilities as to not overwhelm the team with warnings.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Add security scan for the repository

---

.github/workflows/security.yml

This adds a step in the GitHub Actions CI to automatically build the
krakend-ce and builder images and run a security scan on them.
Similarly to the repository scans introduced in a previous PR [1], this
uses Trivy [2] to run the scans, which allows us to add exceptions if
vulnerabilities are not relevant to these images.
[1] https://github.com/krakendio/krakend-ce/pull/650
[2] https://aquasecurity.github.io/trivy/v0.35/
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Add security scanning to container images

---

.github/workflows/release.yml

cosign [1] is a command line utility which will sign a specific
container image given a tag. The signature is pushed to the same
container repository in a specialized tag, and will use the public
sigstore infrastructure to host the signatures in its transparency log,
using the GitHub workflow's credentials.
To verify, do:
```
cosign verify <image reference>
```
The verification also happens from the public transparency log.
[1] https://github.com/sigstore/cosign
[2] https://www.sigstore.dev/

Sign builder images using cosign + sigstore

---

tests/integration.go

Make default backend builder public so it can be reused

Make default backend builder public so it can be reused

---

find_glibc.sh

Fixes #731 by grepping for `ProductVersion:` specifically and squeezing multiple tabs - if any. The script now returns `DARWIN-13.3.1` again, which seems sufficient since a  Rapid Security Response update most likely wouldn't introduce glibc incompatibilities.

Fixing glibc detection on macOS

---

Makefile

A security scan of krakend-2.3.2 shows 6 security vulnerabilities.
These three don't have any fixes yet:
1. LOW: based on github.com/aws/aws-sdk-go [CVE-2020-8912](https://avd.aquasec.com/nvd/cve-2020-8912) 
2. MEDIUM: based on github.com/aws/aws-sdk-go [CVE-2020-8911](https://avd.aquasec.com/nvd/cve-2020-8911) 
3. MEDIUM: based on github.com/gin-gonic/gin [CVE-2023-29401](https://avd.aquasec.com/nvd/cve-2023-29401)
The three that can be mitigated now are:
4. MEDIUM: based on github.com/prometheus/prometheus [CVE-2019-3826](https://avd.aquasec.com/nvd/cve-2019-3826)
This shows a library version v0.40.5 which can be fixed in v2.7.1
The last two are the SSL3 vulnerability:
5. MEDIUM based on libcrypto3 [CVE-2023-1255](https://avd.aquasec.com/nvd/cve-2023-1255)
6. MEDIUM based on libssl3 …

Update to apline-3.18 based image to mitigate SSL3 CVE-2023-1255

---

tests/integration.go

The error message when a received body is empty is a little bit misleading, and looks like the issue is with the json-schema validator creation (like if it was a bug or error in the integrations test code).
With this PR an specific message is added for the empty body, and the wording for the `Validate` result is changed.

improve error message when received body is empty 

---

Makefile

Latest version of cobra already sets the schema url from the version in the environment:
https://github.com/krakend/krakend-cobra/blob/master/check.go#L26 in this line: https://github.com/krakend/krakend-cobra/blob/master/check.go#L77

do not overwrite schema url that is built inside cobra library

---

Makefile

It appears that Alpine 3.18 is no longer available as a Docker image as of 3 weeks ago:
https://github.com/docker-library/golang/commit/cf7a37dedf1fd5a25ca72075645368d1e3c30c4a for more information on Go Docker container change.

Update Go and Alpine versions

---

.github/workflows/security.yml

Also removes the builder scan since it's the official golang docker container and it's not used in runtime.

Add permissions to upload the security reports

---

Makefile

remove setting go version variable at link time
:warning: needs to update dependency to latest lura version that uses runtime to get the go version

remove setting go version variable at link time

---

tests/integration.go

Currently we are using a hardcoded 1.5 seconds wait for the system under test (the KrakenD instance) and the mock backend services to startup. 
However, while that is more than enough for the backend services, the time it takes to start a KrakenD instance depends on how complex or big the config file is. 
With this PR we add several options **for the `krakend-integrations` command**:  https://www.krakend.io/docs/developer/integration-tests/ 
- `krakend_ready_url` : to provide an URL to make requests and wait for the instance to be ready (just by point it to the `/__health` endpoint it will work ok).
- `krakend_ready_url_wait`: to provide a duration of the maximum time we to be polling the `krakend_ready_url` : if after that time we do not succeed to get an Ok response, **it will print a …

Integration test check server started up

---

go.mod
go.sum

Use krakend-cors 2.1.5 , that uses `rs/cors` 1.11.1

update to cors 1.11.1 bug fix for allowed headers
